# Site settings
title: CSS Ruler
description: "Explore CSS lengths."
baseurl: "/css-ruler"
url: "https://katydecorah.com"
permalink: pretty

# Build settings
markdown: kramdown
port: 4000
host: 127.0.0.1

plugin:
- jemoji
- jekyll-sitemap

sass:
  style: :compressed

jquery: 3.3.1
angularjs: 1.6.5
